### ISSUE TITLE
can't edit name when try to add template

### ISSUE THREAD

**Issue by muhammadarif1** [zwieback/FamilyFinance#2]
when i try to add template ,there is option to write a name, when i click keyboard is not showing

**Comment by zwieback** [comment]
What version of the app do you use?

Issue was fixed in [this commit](https://github.com/zwieback/FamilyFinance/commit/d89f2c867e800ef64ed2523f9ca7c239dea5e9a8) (in v1.5.5)

**Comment by zwieback** [comment]
Closed as already fixed and no response.
